const baseData = [{
  "TaskID": 2,
  "OwnerID": 2,
  "PersonIDs": 2,
  "Title": "Kids Baseball Game",
  "RoomID": 2,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-16T08:00:00.000Z",
  "End": "2013-06-16T12:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 3,
  "OwnerID": 2,
  "Title": "Morning Shake",
  "RoomID": 1,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-17T05:00:00.000Z",
  "End": "2013-06-17T06:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 3,
  "OwnerID": 2,
  "Title": "Project Planning",
  "RoomID": 2,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-17T07:00:00.000Z",
  "End": "2013-06-17T09:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 3,
  "OwnerID": 2,
  "Title": "Healthy Lunch",
  "RoomID": 1,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-17T09:00:00.000Z",
  "End": "2013-06-17T10:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 3,
  "OwnerID": 2,
  "Title": "Team Meeting",
  "RoomID": 2,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-17T11:00:00.000Z",
  "End": "2013-06-17T12:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 4,
  "OwnerID": 2,
  "Title": "Morning Shake",
  "RoomID": 1,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-18T05:00:00.000Z",
  "End": "2013-06-18T06:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 4,
  "OwnerID": 2,
  "Title": "Dentists",
  "RoomID": 2,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-18T06:30:00.000Z",
  "End": "2013-06-18T08:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 4,
  "OwnerID": 2,
  "Title": "Customer Meeting",
  "RoomID": 2,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-18T09:00:00.000Z",
  "End": "2013-06-18T10:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 4,
  "OwnerID": 2,
  "Title": "Healthy Lunch",
  "RoomID": 1,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-18T10:00:00.000Z",
  "End": "2013-06-18T11:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 4,
  "OwnerID": 2,
  "Title": "Demo Prep",
  "RoomID": 2,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-18T13:00:00.000Z",
  "End": "2013-06-18T14:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 4,
  "OwnerID": 2,
  "Title": "Meditate",
  "RoomID": 1,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-18T15:00:00.000Z",
  "End": "2013-06-18T16:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 5,
  "OwnerID": 2,
  "Title": "Morning Shake",
  "RoomID": 1,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-19T05:00:00.000Z",
  "End": "2013-06-19T06:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 5,
  "OwnerID": 2,
  "Title": "Demo Meeting",
  "RoomID": 2,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-19T07:00:00.000Z",
  "End": "2013-06-19T08:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 5,
  "OwnerID": 2,
  "Title": "Sales Sync",
  "RoomID": 2,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-19T12:00:00.000Z",
  "End": "2013-06-19T13:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 4,
  "OwnerID": 2,
  "Title": "Healthy Lunch",
  "RoomID": 1,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-19T09:00:00.000Z",
  "End": "2013-06-19T10:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 6,
  "PersonIDs": 2,
  "Title": "Morning Shake",
  "RoomID": 1,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-20T05:00:00.000Z",
  "End": "2013-06-20T06:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 6,
  "PersonIDs": 2,
  "Title": "Company All Hands",
  "RoomID": 2,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-20T07:00:00.000Z",
  "End": "2013-06-20T09:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 6,
  "PersonIDs": 2,
  "Title": "Design Review",
  "RoomID": 2,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-20T11:00:00.000Z",
  "End": "2013-06-20T13:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 4,
  "OwnerID": 2,
  "Title": "Healthy Lunch",
  "RoomID": 1,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-20T09:00:00.000Z",
  "End": "2013-06-20T10:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 4,
  "OwnerID": 2,
  "Title": "Meditate",
  "RoomID": 1,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-20T15:00:00.000Z",
  "End": "2013-06-20T16:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 7,
  "personIDs": 2,
  "Title": "Morning Shake",
  "RoomID": 1,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-21T05:00:00.000Z",
  "End": "2013-06-21T06:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 4,
  "OwnerID": 2,
  "Title": "Healthy Lunch",
  "RoomID": 1,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-21T09:00:00.000Z",
  "End": "2013-06-21T10:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
},{
  "TaskID": 6,
  "PersonIDs": 2,
  "Title": "Retro",
  "RoomID": 2,
  "Description": "Might come to work later!",
  "StartTimezone": null,
  "Start": "2013-06-21T12:00:00.000Z",
  "End": "2013-06-21T14:00:00.000Z",
  "EndTimezone": null,
  "RecurrenceRule": null,
  "RecurrenceID": null,
  "RecurrenceException": null,
  "isAllDay": false
}];
export const customModelFields = {
  id: 'TaskID',
  title: 'Title',
  description: 'Description',
  start: 'Start',
  end: 'End',
  recurrenceRule: 'RecurrenceRule',
  recurrenceId: 'RecurrenceID',
  recurrenceExceptions: 'RecurrenceException'
};
const currentYear = new Date().getFullYear();
const parseAdjust = eventDate => {

  return new Date(eventDate);
  /*
  const date = new Date(eventDate);
  date.setFullYear(currentYear);
  return date;
  */
};
const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
export const displayDate = new Date("2013-06-18");
export const sampleData = baseData.map(dataItem => ({
  id: dataItem.TaskID,
  start: parseAdjust(dataItem.Start),
  startTimezone: dataItem.startTimezone,
  end: parseAdjust(dataItem.End),
  endTimezone: dataItem.endTimezone,
  isAllDay: dataItem.isAllDay,
  title: dataItem.Title,
  description: dataItem.Description,
  recurrenceRule: dataItem.RecurrenceRule,
  recurrenceId: dataItem.RecurrenceID,
  recurrenceExceptions: dataItem.RecurrenceException,
  roomId: dataItem.RoomID,
  ownerID: dataItem.OwnerID,
  personId: dataItem.OwnerID
}));
export const sampleDataWithResources = baseData.map(dataItem => ({
  id: dataItem.TaskID,
  start: parseAdjust(dataItem.Start),
  startTimezone: dataItem.startTimezone,
  end: parseAdjust(dataItem.End),
  endTimezone: dataItem.endTimezone,
  isAllDay: dataItem.isAllDay,
  title: dataItem.Title,
  description: dataItem.Description,
  recurrenceRule: dataItem.RecurrenceRule,
  recurrenceId: dataItem.RecurrenceID,
  recurrenceExceptions: dataItem.RecurrenceException,
  roomId: randomInt(1, 2),
  personId: randomInt(1, 2)
}));
export const sampleDataWithCustomSchema = baseData.map(dataItem => ({
  ...dataItem,
  Start: parseAdjust(dataItem.Start),
  End: parseAdjust(dataItem.End),
}));